[theme]
primaryColor = "#0284C7"
backgroundColor = "#0A0E17"
secondaryBackgroundColor = "#111827"
textColor = "#F8FAFC"
font = "sans serif"

[client]
showSidebarNav = false
toolbarMode = "minimal"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50
